#!/bin/bash
#
#   This file specifies testbecncha and top file, and contains 
#   files to be compiled 
#

TOP_TB="matrix_multiplier_tb"
TOP_TB_MODULE="TOP_MM"
TOP_TB_FILE="$TOP_TB.vhd"

COMPILE_FILES=" $RTL_DIR/matrix_multiplier_pkg.vhd \
                $RTL_DIR/ROM_coeff.vhd
                $RTL_DIR/generic_reg.vhd \
                $RTL_DIR/generic_reg_array.vhd \ 
                $RTL_DIR/generic_reg_matrix.vhd \
                $RTL_DIR/element_multiplier.vhd \
                $RTL_DIR/MU2.vhd \
                $RTL_DIR/MM_op.vhd \
                $RTL_DIR/MM_controller.vhd \
                $RTL_DIR/matrix_multiplier.vhd "

TOP_FILE_B="$RTL_DIR/TOP_MM.vhd"
TOP_FILE_S="$NETLIST_DIR/TOP_synth.v"
TOP_FILE_L="$NETLIST_DIR/TOP_layout.v"
TB_FILES="$RTL_DIR/TB/matrix_multiplier_tb.vhd"

# TODO: ADD pads
LIB_FILES=""

