#!/bin/bash
#
#   This file contains file mapping, and specifies testbecnch and top file 
#

TOP_TB="TOP_TB"	# File name
TOP_TB_MODULE="tb_tip_top" # Entity
TOP_TB_FILE="$TOP_TB.vhd"

COMPILE_FILES=" $RTL_DIR/TIP_TOP.vhd\
                $RTL_DIR/ROM.vhd\
		        $RTL_DIR/Input_matrix.vhd\
		        $RTL_DIR/MAC.vhd\
		        $RTL_DIR/TOP_Accelerator.vhd\
		        $RTL_DIR/Controller.vhd "

TOP_FILE_B="$RTL_DIR/TIP_TOP.vhd" # Top behavioural file
TOP_FILE_S="$NETLIST_DIR/TIP_TOP.v" # Top post-synthesis 
TOP_FILE_L="$NETLIST_DIR/GPLVT_TIP_TOP.v" # Top post-layout
TB_FILES="$RTL_DIR/TOP_TB.vhd"	# List of test-benches

# Additional library files
LIB_FILES="	$RTL_DIR/PADS_Jun2013.v\
		    $RTL_DIR/SPHD110420.v "

SDF_FILE_S="$NETLIST_DIR/top_sdf_synth.sdf"
SDC_FILE="$NETLIST_DIR/top_sdf_synth.sdc"
SDF_FILE_L="$NETLIST_DIR/top_sdf_layout.sdf"
VCD_FILE="$NO_BACKUP_DIR/top_vcd.vcd"
