#!/bin/bash
#
#   Main toolchain script
#

source $SCRIPT_DIR/lib_list
source $SCRIPT_DIR/compile_list

if [ $# -eq 0 ]
then
    echo "Provide an option."
    echo "Available options: sim synth layout power"
elif [ $1 == 'sim' ]
then
    source $SCRIPT_DIR/simulate

elif [ $1 == 'synth' ]
then
    source $SCRIPT_DIR/synthesis

elif [ $1 == 'layout' ]
then
    source $SCRIPT_DIR/layout

elif [ $1 == 'power' ]
then
    source $SCRIPT_DIR/power

else
    echo "Invalid option."
    echo "Available options: sim synth layout power"
fi
