#!/bin/bash
#
#   This file contains different power-voltage libary paths 
#

export CLK_LIB_LPHVT=$STM065_DIR/CLOCK65LPHVT_3.1/libs
export CLK_LIB_LPSVT=$STM065_DIR/CLOCK65LPSVT_3.1/libs
export CLK_LIB_LPLVT=$STM065_DIR/CLOCK65LPLVT_3.1/libs

export BUF_LIB_LPHVT=$STM065_DIR/CORE65LPHVT_5.1/libs
export BUF_LIB_LPSVT=$STM065_DIR/CORE65LPSVT_5.1/libs
export BUF_LIB_LPLVT=$STM065_DIR/CORE65LPLVT_5.1/libs

# TODO:
# export PADS_LIB=$PADS_DIR