#!/bin/bash
#
#   This file contains prefered library options
#

# Type options:
#   GPLVT GPSVT LPHVT LPLVT LPSVT
export LIB_TYPE="LPHVT"

# Case options:
#   bc nom wc
export LIB_CASE="bc"

# Voltage options (V):
export LIB_VOLTAGE="1.05"

## Temperature options (C):
export LIB_TEMP="105"

