#!/bin/bash
#
#   This file contains settings for different simulations
#

SIM_SYNTH_OPT=" -t 1ps \
                +nowarn8470 \
                +nowarn8470 \ 
                -sdftyp /$TOP_TB/$TOP_TB_MODULE=$SDF_FILE_S"

SIM_LAYOUT_OPT="-t 1ps \
                +nowarn8470 \
                +nowarn8470 \ 
                -sdftyp /$TOP_TB/$TOP_TB_MODULE=$SDF_FILE_L"


