#!/bin/bash
#
#   Simulation script
#

read -p 'Choose simulation mode (b s l v): ' mode

cd $SIM_DIR
rm -Rf *
test -f modelsim.ini || cp $MODEL_SIM/modelsim_st65.ini ./modelsim.ini
test -d reports || mkdir ./reports
export SIM_REPORTS=$SIM_DIR/reports

libraries="-L CORE65LPHVT \
           -L CLOCK65LPHVT \
           -L PRHS65 "

case $mode in
    b)
        vlib work
        vlog -work work $LIB_FILES
        vcom -work work $COMPILE_PKGS $COMPILE_FILES $TOP_FILE_B $TB_FILES 
	    echo "Simulating behavioural model"
        vsim work.$TOP_TB_MODULE -do $SCRIPT_DIR/waves.do
	;;
    s)
        vlib work
        # TODO: Depending on power-voltage choice append to LIB_FILES
        # LIB_FILES = "$LIB_FILES"
        vlog -work work $LIB_FILES $TOP_FILE_S
        vcom -work work $COMPILE_PKGS $TB_FILES 
        echo "Simulating post-synthesis"
        # TODO: Add options for sdf input
        vsim $libraries work.$TOP_TB_MODULE -do $SCRIPT_DIR/waves.do
	;;
    l)
        vlib work
        # TODO: Depending on power-voltage choice append to LIB_FILES
        # LIB_FILES = "$LIB_FILES"
        vlog -work work $LIB_FILES $TOP_FILE_L
    	vcom -work work $TB_FILES 
        echo "Simulating post-layout"
        # TODO: Add options for sdf input
        vsim work.$TOP_TB_MODULE -do $SCRIPT_DIR/waves.do
	;;
    v)
        vlib work
        vlog -work work $LIB_FILES $TOP_FILE_L
    	vcom -work work $TB_FILES 
        echo "Generating VCD file"
        # TODO: Add options for sdf input
        vsim work.$TOP_TB_MODULE -do $SCRIPT_DIR/vcd.do > $SIM_REPORTS/vcd.log
	;;
    *)
	    echo "Invalid sim option."
    	echo "Available options are: b s l v"
	;;
esac
