#!/bin/bash
#
# Simulation script
#
read -p 'Choose simulation mode (r, s, l): ' mode

case $mode in
    r)
	echo "Simulating RTL"
    	# TODO
	# vlib 
	# vlog
	# vsim top -do $SCRIPT_DIR/waves.do
	;;
    s)
	echo "Simulating post-synthesis!!!"
    	# TODO
	;;
    l)
	echo "Simulating post-layout"
    	# TODO
	;;
    *)
	echo "Invalid sim option."
    	echo "Available options are: r s l"
	;;
esac

# source $SCRIPT_DIR/waves
